### ISSUE TITLE
Implement "All Orders Summary"

### ISSUE THREAD

**Issue by ezl** [howdykolache/abdulaziz-frontend-rewrite#12]
this is same as delivery summary, but different client types. should be all same code with just a filter for which client types we actually pull

same design as delivery summary page also. Figma link to design:
https://www.figma.com/file/SxVIaCOmbRDrOD0To1ogG7/Howdy-'22-Q1-(Kris-Working-Version-For-Ordering-App)?node-id=4866%3A1307

**Comment by yassinya** [comment]
@ezl I unfortunately see no difference between Delivery Summary and All Orders Summary design. Both pages have a filter for client types
Do you mean there is a difference in displayed/available options (client types)?

**Comment by ezl** [comment]
I apologize! you are correct!

In the original version, there is no filter for client types, so that was hard coded.

In the new version, since there are client type filters, it is no longer necessary to have separate pages. :) 

I will close this ticket, since it is unnecessary.
